spring.application.name=api-rest

# --- CONFIGURACIÓN DE AIVEN (NUBE) ---
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- CONFIGURACIÓN DE HIBERNATE (JPA) ---
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- JWT (JSON Web Token) ---
# Ahora espera una variable del sistema, si no la encuentra usa una de prueba (útil para localhost)
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# --- LOGS ---
logging.level.org.springframework=DEBUG
logging.level.com.bidco=DEBUG

# --- TAMAÑO MÁXIMO IMÁGENES ---
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# --- CLOUDINARY ---
# El cloud_name no es un secreto crítico, se puede dejar, pero las API keys sí lo son
cloudinary.cloud_name=dwgi3kagx
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}
