spring.application.name=api-rest

# --- CONFIGURACIÓN DE AIVEN (NUBE) ---
# Hemos cambiado localhost por el host de Aiven y el puerto 19341
spring.datasource.url=jdbc:mysql://mysql-bidco-bidco.f.aivencloud.com:19341/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- CONFIGURACIÓN DE HIBERNATE (JPA) ---
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
# Cambiamos 'none' por 'update' para que Hibernate cree las tablas si no existen en Aiven
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- JWT (JSON Web Token) ---
jwt.secret=0wLqYh8jJkZ2tP7bA1mN6cV4xR9gUvW3eSrQyDfGhX5uJpMnBvCtFzHlIoK0iEaTd
jwt.expiration=86400000

# --- LOGS ---
logging.level.org.springframework=DEBUG
logging.level.com.bidco=DEBUG

# --- TAMAÑO MÁXIMO IMÁGENES ---
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# CLOUDINARY
cloudinary.cloud_name=dwgi3kagx
cloudinary.api_key=434438643452211
cloudinary.api_secret=1FStO-x19WMJEW9MekEfQfNt8V4